{
	"id": 14774,
	"date": "2019-01-06T15:46:36",
	"date_gmt": "2019-01-06T20:46:36",
	"guid": {
		"rendered": "http:\/\/course-introduction-orientation"
	},
	"modified": "2019-01-07T14:07:17",
	"modified_gmt": "2019-01-07T19:07:17",
	"slug": "web-115-course-introduction",
	"status": "publish",
	"type": "lp_lesson",
	"link": "https:\/\/dev01.inside-out-project.com\/courses\/web-115\/lessons\/web-115-course-introduction\/",
	"title": {
		"rendered": "Course Introduction"
	},
	"content": {
		"rendered": "<p>This course teaches students to use Adobe Dreamweaver CC, the industry standard web design application. Students will design and author a web site that is user-friendly, portable, and easy to modify. Topics of this course include the use of tables for flexible layout and design, Cascading Style Sheets (CSS), selected JavaScript behaviors, the appropriate use of color, and effective navigation strategies. At the completion of the course, students will have designed, created, and tested a Web site.<\/p>\n<p>While web page developers need to understand HTML (Hypertext Markup Language), they should also be knowledgeable about the use of WYSIWYG editors. Macromedia Dreamweaver is an industry standard, leading web development application for Web design, maintenance, and site management. Throughout the course, the student will use the WYSIWYG capabilities of Dreamweaver while still editing the underlying HTML code when necessary.<\/p>\n<p><script src=\"https:\/\/dev01.inside-out-project.com\/iop_app\/iop_lp_widget_v-1.0.0.4\/iop_lp_widget_pods_template.js\"><\/script><\/p>\n",
		"protected": false
	},
	"parent": 0,
	"comment_status": "open",
	"ping_status": "closed",
	"template": "",
	"format": "standard",
	"blooms_cognitive_process": [],
	"knowledge_focus": [],
	"learning_objectives": false,
	"featured_video": [{
		"url": "https:\/\/www.youtube.com\/embed\/sRgMELgCm7I",
		"resource_id": "sRgMELgCm7I",
		"resource_screen_shot": "",
		"courses_used_in": [],
		"lessons_featured_in": {
			"14775": {
				"learning_objectives": false,
				"featured_video": {
					"ID": "10759",
					"post_author": "1",
					"post_date": "2018-02-21 19:14:20",
					"post_date_gmt": "2018-02-22 00:14:20",
					"post_content": "coming soon filler for inside out project lesson videos that are in production or slated for production.",
					"post_title": "inside-out-project-coming-soon",
					"post_excerpt": "",
					"post_status": "publish",
					"comment_status": "open",
					"ping_status": "closed",
					"post_password": "",
					"post_name": "inside-out-project-coming-soon",
					"to_ping": "",
					"pinged": "",
					"post_modified": "2018-02-21 19:14:20",
					"post_modified_gmt": "2018-02-22 00:14:20",
					"post_content_filtered": "",
					"post_parent": "0",
					"guid": "https:\/\/dev01.inside-out-project.com\/?post_type=knowledge_resource&#038;p=10759",
					"menu_order": "0",
					"post_type": "knowledge_resource",
					"post_mime_type": "",
					"comment_count": "0",
					"pod_item_id": "10759"
				},
				"lesson_resources": false,
				"additional_resources": false,
				"presentation_notes": "",
				"ID": 14775,
				"post_title": "From The Instructor",
				"post_content": "<p>The primary learning objective of this course is to expand a deeper understanding of web application development while gaining a deeper knowledge of HTML5. This course has two per-requisites, WEB-100 and being able to use a computer and web browser. We keep things simple because we truly want \u201cEveryone\u201d to learn! Under \u201cModules\u201d the entire course has been laid out in a proprietary order that will guide you through all the learning objectives. Each of the learning objectives has one or more exercise and\/or an assessment quiz that you will do to work through the course. You can track your progress in the \u201cGrades\u201d section of Canvas. You should expect to spend 3-5 hours per a week in this course. An important technique, if you find yourself struggling with the material, is to jump back and re-do an earlier section. Having a solid understanding of all the ideas in the course is more important than getting through the course successfully. As the Instructor, I will monitor the \u201cHelp Forum\u201d from time to time, but for this course to scale, it will be important that the participants in the course help each other. You must say \u2018hi\u2019 to your fellow students in the \u201cIntroduce Yourself\u201d discussion.<\/p>\r\n<p><script src=\"https:\/\/dev01.inside-out-project.com\/iop_app\/iop_lp_widget_v-1.0.0.4\/iop_lp_widget_pods_template.js\"><\/script><\/p>",
				"post_excerpt": "",
				"post_author": "2",
				"post_date": "2019-01-06 15:46:51",
				"post_date_gmt": "2019-01-06 20:46:51",
				"post_status": "publish",
				"comment_status": "open",
				"ping_status": "closed",
				"post_password": "",
				"post_name": "web-115-from-the-instructor",
				"to_ping": "",
				"pinged": "",
				"post_modified": "2019-01-15 07:48:23",
				"post_modified_gmt": "2019-01-15 12:48:23",
				"post_content_filtered": "",
				"post_parent": 0,
				"guid": "http:\/\/start-here-from-the-instructor",
				"menu_order": 0,
				"post_type": "lp_lesson",
				"post_mime_type": "",
				"comment_count": "0",
				"comments": false,
				"blooms_cognitive_process": false,
				"knowledge_focus": false,
				"id": 14775
			},
			"14774": {
				"learning_objectives": false,
				"featured_video": {
					"ID": "10759",
					"post_author": "1",
					"post_date": "2018-02-21 19:14:20",
					"post_date_gmt": "2018-02-22 00:14:20",
					"post_content": "coming soon filler for inside out project lesson videos that are in production or slated for production.",
					"post_title": "inside-out-project-coming-soon",
					"post_excerpt": "",
					"post_status": "publish",
					"comment_status": "open",
					"ping_status": "closed",
					"post_password": "",
					"post_name": "inside-out-project-coming-soon",
					"to_ping": "",
					"pinged": "",
					"post_modified": "2018-02-21 19:14:20",
					"post_modified_gmt": "2018-02-22 00:14:20",
					"post_content_filtered": "",
					"post_parent": "0",
					"guid": "https:\/\/dev01.inside-out-project.com\/?post_type=knowledge_resource&#038;p=10759",
					"menu_order": "0",
					"post_type": "knowledge_resource",
					"post_mime_type": "",
					"comment_count": "0",
					"pod_item_id": "10759"
				},
				"lesson_resources": false,
				"additional_resources": false,
				"presentation_notes": "",
				"ID": 14774,
				"post_title": "Course Introduction",
				"post_content": "<p>This course teaches students to use Adobe Dreamweaver CC, the industry standard web design application. Students will design and author a web site that is user-friendly, portable, and easy to modify. Topics of this course include the use of tables for flexible layout and design, Cascading Style Sheets (CSS), selected JavaScript behaviors, the appropriate use of color, and effective navigation strategies. At the completion of the course, students will have designed, created, and tested a Web site.<\/p>\r\n<p>While web page developers need to understand HTML (Hypertext Markup Language), they should also be knowledgeable about the use of WYSIWYG editors. Macromedia Dreamweaver is an industry standard, leading web development application for Web design, maintenance, and site management. Throughout the course, the student will use the WYSIWYG capabilities of Dreamweaver while still editing the underlying HTML code when necessary.<\/p>\r\n<script src=\"https:\/\/dev01.inside-out-project.com\/iop_app\/iop_lp_widget_v-1.0.0.4\/iop_lp_widget_pods_template.js\"><\/script>\r\n",
				"post_excerpt": "",
				"post_author": "2",
				"post_date": "2019-01-06 15:46:36",
				"post_date_gmt": "2019-01-06 20:46:36",
				"post_status": "publish",
				"comment_status": "open",
				"ping_status": "closed",
				"post_password": "",
				"post_name": "web-115-course-introduction",
				"to_ping": "",
				"pinged": "",
				"post_modified": "2019-01-07 14:07:17",
				"post_modified_gmt": "2019-01-07 19:07:17",
				"post_content_filtered": "",
				"post_parent": 0,
				"guid": "http:\/\/course-introduction-orientation",
				"menu_order": 0,
				"post_type": "lp_lesson",
				"post_mime_type": "",
				"comment_count": "0",
				"comments": false,
				"blooms_cognitive_process": false,
				"knowledge_focus": false,
				"id": 14774
			}
		},
		"lessons_required_in": [],
		"lessons_used_in": {
			"10753": {
				"learning_objectives": false,
				"featured_video": false,
				"lesson_resources": [{
					"ID": "10759",
					"post_author": "1",
					"post_date": "2018-02-21 19:14:20",
					"post_date_gmt": "2018-02-22 00:14:20",
					"post_content": "coming soon filler for inside out project lesson videos that are in production or slated for production.",
					"post_title": "inside-out-project-coming-soon",
					"post_excerpt": "",
					"post_status": "publish",
					"comment_status": "open",
					"ping_status": "closed",
					"post_password": "",
					"post_name": "inside-out-project-coming-soon",
					"to_ping": "",
					"pinged": "",
					"post_modified": "2018-02-21 19:14:20",
					"post_modified_gmt": "2018-02-22 00:14:20",
					"post_content_filtered": "",
					"post_parent": "0",
					"guid": "https:\/\/dev01.inside-out-project.com\/?post_type=knowledge_resource&#038;p=10759",
					"menu_order": "0",
					"post_type": "knowledge_resource",
					"post_mime_type": "",
					"comment_count": "0",
					"pod_item_id": "10759"
				}],
				"additional_resources": false,
				"presentation_notes": "",
				"ID": 10753,
				"post_title": "<i class=\"fa fa-pencil\"><\/i> Login To A Dashboard",
				"post_content": "In this step we begin developing our JavaScript application by laying out our initial files, setting up out index.html file, and start placing elements in our page through manipulating the DOM.\r\n<h3>Action Items to Complete<\/h3>\r\n<ol>\r\n \t<li>Complete all steps completed in the video \u201cinside out \u2013 STEP 401 | Login To A Dashboard\u201d.\r\n<ul id=\"videoLinks\">\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=0s\">00:00 - Introduction <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=33s\">00:33 - project step overview <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=130s\">02:10 - create our index.html page <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=160s\">02:40 - add the viewport meta tag <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=211s\">03:31 - go to cloudflare.com to get animate.css <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=231s\">03:51 - search for animate.css on cloudflare.com <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=236s\">03:56 - copy animate.css link from cloudflare <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=248s\">04:08 - link animate.css in our index.html file <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=282s\">04:42 - create the assets folder <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=291s\">04:51 - create the assets\/js folder <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=294s\">04:54 - create the assets\/js\/app.js file <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=314s\">05:14 - look at how in DW we access linked files <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=342s\">05:42 - link assets\/js\/app.js file to index.html <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=398s\">06:38 - begin coding in assets\/js\/app.js file <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=417s\">06:57 - add 'use strict'; to app.js <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=449s\">07:29 - add the applicationTitle variable <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=489s\">08:09 - add the applicationTagLine variable <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=607s\">10:07 - add the function initializeApplication() <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=646s\">10:46 - add document.title = applicationTitle; <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=717s\">11:57 - add the window.addEventListener <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=822s\">13:42 - add the document.body.styles <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=958s\">15:58 - add the var elWrapper <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=1165s\">19:25 - add the var elHeader <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=1263s\">21:03 - add the var elHeaderTitle <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=1432s\">23:52 - add the var elHeaderTagLine <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=1604s\">26:44 - add elHeaderTagLine.style.fontSize <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=1660s\">27:40 - add the var elMain <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=1732s\">28:52 - add the var elFooter <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=1815s\">30:15 - add the animate css to the elements <\/a><\/li>\r\n \t<li><a href=\"https:\/\/www.youtube.com\/watch?v=yNO7bGcy-mo&amp;t=1955s\">32:35 - clean up code<\/a><\/li>\r\n<\/ul>\r\n<\/li>\r\n \t<li>Add &amp; commit your work in your repository and then push your work to GitHub.<\/li>\r\n \t<li>Comment a link to your repository in the\u00a0bottom of the body of your index.html page.<\/li>\r\n \t<li>Put all the files you have created to your server and review that your work is error free and aligns to the completed work in the video.<\/li>\r\n \t<li>Submit the url to your application (the index.html file) once you have validated your work and are confident you have completed everything. The link should look similar to the following link:\u00a0<a href=\"http:\/\/step-401.inside-out-project.com\" target=\"_blank\" rel=\"noopener noreferrer\">https:\/\/step-401.inside-out-project.com<\/a>\u00a0and\u00a0your page should look to what you see when clicking on the example link.<\/li>\r\n<\/ol>\r\n<ul class=\"lessonResourceLinks\">\r\n \t<li><a class=\"btn btn-lg btn-default\" href=\"http:\/\/step-401.inside-out-project.com\/\" target=\"_blank\" rel=\"noopener noreferrer\"><i class=\"fa fa-chrome fa-1x\"><\/i> Step Example<\/a><\/li>\r\n \t<li><a class=\"btn btn-lg btn-default\" href=\"https:\/\/github.com\/inside-out-project\/step-400\/tree\/step-401\" target=\"_blank\" rel=\"noopener noreferrer\"><i class=\"fa fa-github fa-1x\"><\/i> Step Repository<\/a><\/li>\r\n \t<li><a class=\"btn btn-lg btn-default\" href=\"https:\/\/dev01.inside-out-project.com\/forums\/forum\/inside-out-project-iop-4xx\/\/\" target=\"_blank\" rel=\"noopener noreferrer\"><i class=\"fa fa-wpforms fa-1x\"><\/i> inside out project | IOP-4XX Forum<\/a><\/li>\r\n<\/ul>\r\n<blockquote>\r\n<h6>please note: your assignment is to be submitted in the step folder as shown in the example above.<\/h6>\r\n<\/blockquote>\r\n<h4 style=\"text-align: center;\"><span style=\"color: #ff0000;\"><strong>RACC STUDENTS: Please review the rubric for this assignment and submit this assignment in Canvas.<\/strong><\/span><\/h4>\r\n[pods name=\"knowledge_resource\" where=\"lessons_used_in.ID = 10753\" template=\"Lesson Resources Template\"]",
				"post_excerpt": "",
				"post_author": "1",
				"post_date": "2018-02-21 16:29:00",
				"post_date_gmt": "2018-02-21 21:29:00",
				"post_status": "publish",
				"comment_status": "open",
				"ping_status": "closed",
				"post_password": "",
				"post_name": "login-to-a-dashboard",
				"to_ping": "",
				"pinged": "",
				"post_modified": "2018-02-21 19:19:13",
				"post_modified_gmt": "2018-02-22 00:19:13",
				"post_content_filtered": "",
				"post_parent": 0,
				"guid": "http:\/\/login-to-a-dashboard",
				"menu_order": 0,
				"post_type": "lp_lesson",
				"post_mime_type": "",
				"comment_count": "0",
				"comments": false,
				"blooms_cognitive_process": false,
				"knowledge_focus": false,
				"id": 10753
			}
		},
		"learning_objectives_required_in": [],
		"learning_objectives_used_in": [],
		"learning_objective_featured_in": [],
		"ID": 10759,
		"post_title": "inside-out-project-coming-soon",
		"post_content": "coming soon filler for inside out project lesson videos that are in production or slated for production.",
		"post_excerpt": "",
		"post_author": "1",
		"post_date": "2018-02-21 19:14:20",
		"post_date_gmt": "2018-02-22 00:14:20",
		"post_status": "publish",
		"comment_status": "open",
		"ping_status": "closed",
		"post_password": "",
		"post_name": "inside-out-project-coming-soon",
		"to_ping": "",
		"pinged": "",
		"post_modified": "2018-02-21 19:14:20",
		"post_modified_gmt": "2018-02-22 00:14:20",
		"post_content_filtered": "",
		"post_parent": [],
		"guid": "https:\/\/dev01.inside-out-project.com\/?post_type=knowledge_resource&#038;p=10759",
		"menu_order": 0,
		"post_type": "knowledge_resource",
		"post_mime_type": "",
		"comment_count": "0",
		"comments": false,
		"blooms_cognitive_process": false,
		"knowledge_focus": false,
		"knowledge_resource_format": [{
			"term_id": "116",
			"name": "YouTube",
			"slug": "youtube",
			"term_group": "0",
			"term_taxonomy_id": "116",
			"taxonomy": "knowledge_resource_format",
			"description": "YouTube Video link",
			"parent": "0",
			"count": "201",
			"object_id": "22324",
			"term_order": "0",
			"pod_item_id": "116"
		}],
		"resource_site": false,
		"id": 10759
	}],
	"lesson_resources": false,
	"additional_resources": false,
	"presentation_notes": "",
	"_links": {
		"self": [{
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/lp_lesson\/14774"
		}],
		"collection": [{
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/lp_lesson"
		}],
		"about": [{
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/types\/lp_lesson"
		}],
		"replies": [{
			"embeddable": true,
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/comments?post=14774"
		}],
		"version-history": [{
			"count": 5,
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/lp_lesson\/14774\/revisions"
		}],
		"predecessor-version": [{
			"id": 14795,
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/lp_lesson\/14774\/revisions\/14795"
		}],
		"wp:attachment": [{
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/media?parent=14774"
		}],
		"wp:term": [{
			"taxonomy": "blooms_cognitive_process",
			"embeddable": true,
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/blooms_cognitive_process?post=14774"
		},
		{
			"taxonomy": "knowledge_focus",
			"embeddable": true,
			"href": "https:\/\/dev01.inside-out-project.com\/wp-json\/wp\/v2\/knowledge_focus?post=14774"
		}],
		"curies": [{
			"name": "wp",
			"href": "https:\/\/api.w.org\/{rel}",
			"templated": true
		}]
	}
}